server:
  port: 7130


spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/SH-ANALYSIS-DB

  cloud:
    compatibility-verifier:
      enabled: false

  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:1234@localhost:8761/eureka/

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        eventConsumerBufferSize: 10