server:
  port: 7130


spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/SH-ANALYSIS-DB

  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:1234@localhost:7010/eureka/