server:
  port: 7060

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BILLING-DB
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySql5Dialect
          format_sql: true
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:1234@localhost:8761/eureka/