server:
  port: 7070

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/SH-CLIENT-DB

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:1234@localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"


jwt:
  access: "test"
