server:
  port: 7010

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  username: ${EUREKA_USERNAME:eureka}
  password: ${EUREKA_PASSWORD:1234}

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411