server:
  port: 7020

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:1234@localhost:8761/eureka/

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          - gateway:
            route:
              RouteDefinitionLocator: INFO 
          - gateway: TRACE

spring:
  cloud:
    gateway:
      routes:
        #order service API
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path= /api/order-line/**, /api/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: inventoryService
                fallbackUri: forward:/inventoryServiceFallback

        #product service API
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path= /api/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: inventoryService
                fallbackUri: forward:/inventoryServiceFallback

        #inventory service API
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path= /api/inventory/**

  security:
    oauth2:
      resourceServer:
        jwt:
          issuer-uri: http://localhost:8080/realms/shopping-realm
          jwk-set-url: ${spring.security.oauth2.resourceServer.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: order-client
      principal-attribute: preferred_name

resilience4j:
  circuitbreaker:
    instances:
      inventoryService:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        eventConsumerBufferSize: 10