server:
  port: 7020

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7010/eureka/

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          - gateway:
            route:
              RouteDefinitionLocator: INFO
          - gateway: TRACE

spring:
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://ORDER-SERVICE
            - predicates: Path= api/order-line, api/order