server:
  port: 7120


spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/SH-INVENTORY-DB

eureka:
  client:
    serviceUrl:
      defaultZone:  http://eureka:1234@localhost:7010/eureka/
