server:
  port: 0


spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/SH-INVENTORY-DB

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:7010/eureka/
