server:
  port: 7120


spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/SH-INVENTORY-DB

  cloud:
    compatibility-verifier:
      enabled: false

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone:  http://eureka:1234@localhost:8761/eureka/
