server:
  port: 7150

#discovery client properties
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:1234@localhost:8761/eureka/

#actuator properties
management:
  endpoints:
    web:
      exposure:
        include: "*"

#kafka properties
spring:
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    consumer:
      key-deserializer: org.apache.kafka.common.deserialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.deserializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.shoppingms.notificationservice.dto.OrderPlacedEvent
