server:
  port: 7140

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/SH-ORDER-DB

eureka:
  client:
    serviceUrl:
      defaultZone:  http://eureka:1234@localhost:7010/eureka/

logging:
  level:
    io.github.resilience4j: DEBUG


#actuator
management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

#resilience4j properties
resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        eventConsumerBufferSize: 10
