server:
  port: 7140

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/SH-ORDER-DB

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7010/eureka/

microservice:
  name:
    product: PRODUCT-SERVICE
    inventory: INVENTORY-SERVICE