server:
  port: 7140

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/SH-ORDER-DB

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7010/eureka/

#actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

#resilience4j properties
resilience4j:
  circuit-breaker:
    instances:
      inventory:
        - registerHealthIndicator: true
        - event-consumer-buffer-size: 10
        - slidingWindowType: COUNT_BASED
        - slidingWindowSize: 5
        - failureRateThreshold: 50
        - waitDurationInOpenState: 5s
        - permittedNumberOfCallsInHalfOpenState: 3
        - automaticTransitionFromOpenToHalfOpenEnabled: true