server:
  port: 7100

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/SH-PRODUCT-DB

  cloud:
    compatibility-verifier:
      enabled: false

  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411


eureka:
  client:
    serviceUrl:
      defaultZone:  http://eureka:1234@localhost:7010/eureka/
