server:
  port: 7100

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/SH-PRODUCT-DB

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7010/eureka/

product-service:
  ribbon:
    listOfServers: localhost:7121, localhost:7122